# https://github.com/actions/javascript-action
# https://github.com/actions/typescript-action
name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs: 
  input_one:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'

