name: Annotations

on: [push, pull_request, workflow_dispatch]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
        - name: Display workflow commands error and warn
          run: |
            echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
            echo "::error file=app.js,line=7,col=5,endColumn=7::Error in app.js"
            