name: My First Workflow

on:
    push:
        branches:
            - 'main'
            - 'releases/**'
        paths:
            - 'doc/**'
    schedule:
        # Runs at every 15th minute
        - cron: '*/15 * * * *'
        # Runs every hour from 9am to 5pm
        - cron: '0 9-17 * * *'
        # Runs every Friday at midnight
        - cron: '0 0 * * FRI'
        # Runs every quarter (00:00 on day 1 every 3rd month)
        - cron: '0 0 1 */3 *'

    workflow_dispatch:
        inputs:
            homedrive:
              description: 'The home drive of the machine'
              required: true
            logLevel:
              description: 'Log level'
              default: 'warning'
              type: choice
              options:
                - info
                - warning
                - debug
            tag:
              description: 'Apply tag after successful test run'
              required: true
              type: boolean
              default: true
            environment:
              description: 'Environment to run tests against'
              type: environment
              required: true
 
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "👋 Hello World!"
     
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: List files in the repository
        run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree   
