name: My Sixth Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        if: ${{ github.ref == 'refs/heads/main'}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying branch to ${{ github.ref }} "