name: My Third Workflow

on:

    workflow_dispatch:

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Clean install depencencies and build
              run: |
                npm install
                npm run build
              working-directory: ./temp
              shell: bash

            - run: print %ENV
              shell: perl {0}
