name: Settings Secrets And Variables

on: [push]

jobs:
    settings_secrets_and_variables:
        runs-on: ubuntu-latest
        steps:
            - name: Set secret and var as input
              uses: ActionsInAction/HelloWorld@v1
              with:
                    MY_SECRET: ${{ secrets.secret_name }}
                    MY_VAR: ${{ vars.variable_name }}
